import type {
  Competidor,
  DiagnosticoSemanal,
  Gancho,
  Idea,
  PiezaContenido,
  PiezaMetrica,
  Tendencia,
} from "./types";

/*
 * Datos iniciales del tablero.
 *
 * IMPORTANTE — política de datos (decisión de producto):
 *  - MÉTRICAS y COMPETENCIA arrancan VACÍAS a propósito. Son datos sobre la
 *    realidad (tu rendimiento real, cuentas reales) y NO deben inventarse.
 *    Los llenas tú con datos reales desde la propia interfaz.
 *  - GANCHOS, CONTENIDO, TENDENCIAS e IDEAS traen ejemplos de muestra (swipe
 *    file / plantillas de inspiración). Son contenido editorial, no afirman
 *    nada sobre tu cuenta. La UI los marca con la etiqueta "Ejemplo".
 *
 * Reemplaza este archivo por llamadas a tu base de datos (ver CLAUDE.md).
 */

// ============================ 1. GANCHOS (ejemplos) ============================

export const ganchos: Gancho[] = [
  {
    id: "g_001",
    texto: "No estás cansado. Estás evitando una conversación contigo mismo.",
    nicho: "ansiedad",
    emocion: "verdad",
    tipo: "No estás cansado, estás [X]",
    nivelDolor: 9,
    nivelCuriosidad: 8,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-10",
    estado: "pendiente",
  },
  {
    id: "g_002",
    texto: "Tu negocio crece, pero tu paz no. Y nadie te avisó que eso tenía precio.",
    nicho: "negocio",
    emocion: "vacío",
    tipo: "Tu negocio crece, pero tu paz no",
    nivelDolor: 8,
    nivelCuriosidad: 7,
    formato: "carrusel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-08",
    estado: "pendiente",
  },
  {
    id: "g_003",
    texto: "Eso que llamas ambición, a veces, solo es una herida con horario de oficina.",
    nicho: "trauma",
    emocion: "dolor",
    tipo: "Eso que llamas ambición también puede ser trauma",
    nivelDolor: 10,
    nivelCuriosidad: 9,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-14",
    estado: "adaptar",
  },
  {
    id: "g_004",
    texto: "No es disciplina. Es huida con buena reputación.",
    nicho: "disciplina",
    emocion: "verdad",
    tipo: "No es disciplina, es huida",
    nivelDolor: 8,
    nivelCuriosidad: 9,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-06",
    estado: "pendiente",
  },
  {
    id: "g_005",
    texto: "No quieres amor. Quieres alguien que te anestesie el vacío sin hacer preguntas.",
    nicho: "relaciones",
    emocion: "dolor",
    tipo: "No quieres amor, quieres anestesia",
    nivelDolor: 10,
    nivelCuriosidad: 8,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-02",
    estado: "pendiente",
  },
  {
    id: "g_006",
    texto: "Nadie te dice esto sobre el éxito: te vuelve más eficiente para escapar de ti.",
    nicho: "ego",
    emocion: "verdad",
    tipo: "Nadie te dice esto sobre [X]",
    nivelDolor: 7,
    nivelCuriosidad: 9,
    formato: "thread",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-12",
    estado: "pendiente",
  },
  {
    id: "g_007",
    texto: "Dejá de llamar 'productividad' a tu forma de no sentir.",
    nicho: "autosabotaje",
    emocion: "culpa",
    tipo: "Dejá de hacer [X]",
    nivelDolor: 8,
    nivelCuriosidad: 7,
    formato: "story",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-13",
    estado: "pendiente",
  },
  {
    id: "g_008",
    texto: "El problema no es tu falta de foco. Es lo que sentirías si te detuvieras.",
    nicho: "ansiedad",
    emocion: "miedo",
    tipo: "El problema no es [X], es [Y]",
    nivelDolor: 9,
    nivelCuriosidad: 9,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-04",
    estado: "pendiente",
  },
  {
    id: "g_009",
    texto: "El control está matando tu capacidad de recibir.",
    nicho: "sombra",
    emocion: "miedo",
    tipo: "[X] está matando tu [Y]",
    nivelDolor: 7,
    nivelCuriosidad: 8,
    formato: "carrusel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-11",
    estado: "pendiente",
  },
  {
    id: "g_010",
    texto: "7 cosas que ojalá hubiera sabido antes de construir un negocio para huir de mí.",
    nicho: "negocio",
    emocion: "esperanza",
    tipo: "[Número] cosas que ojalá hubiera sabido",
    nivelDolor: 6,
    nivelCuriosidad: 9,
    formato: "carrusel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-09",
    estado: "pendiente",
  },
  {
    id: "g_011",
    texto: "Tu identidad no es quién eres. Es quién aprendiste a fingir para sobrevivir.",
    nicho: "identidad",
    emocion: "verdad",
    tipo: "Nadie te dice esto sobre [X]",
    nivelDolor: 9,
    nivelCuriosidad: 8,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-15",
    estado: "adaptar",
  },
  {
    id: "g_012",
    texto: "La espiritualidad de moda te vendió calma. Lo que necesitabas era verdad.",
    nicho: "espiritualidad",
    emocion: "rabia",
    tipo: "El problema no es [X], es [Y]",
    nivelDolor: 7,
    nivelCuriosidad: 8,
    formato: "reel",
    fuente: "Ejemplo",
    link: "",
    vistas: 0,
    guardados: 0,
    compartidos: 0,
    fechaGuardada: "2026-06-14",
    estado: "pendiente",
  },
];

// ============================ 2. MÉTRICAS ============================
// Vacío a propósito: aquí solo van TUS métricas reales (las registras desde
// la página "Métricas" con el botón "Registrar pieza"). Nada inventado.

export const piezasMetrica: PiezaMetrica[] = [];

// ============================ 3. COMPETENCIA ============================
// Vacío a propósito: agrega cuentas reales que sigues desde la página
// "Rastreador de Competencia" (botón "Competidor" y "Pegar reel").

export const competidores: Competidor[] = [];

// ============================ 4/5. CONTENIDO + CALENDARIO (ejemplos) ============================

export const piezasContenido: PiezaContenido[] = [
  {
    id: "p_001",
    tituloInterno: "Reel — La quietud que evitas",
    hook: "El problema no es tu falta de foco. Es lo que sentirías si te detuvieras.",
    guion:
      "Hook directo + golpe psicológico sobre el miedo a la quietud. Desarrollo con ejemplo del dueño que llena la agenda. Giro: el foco no se entrena, se deja de huir. CTA a DM.",
    descripcion:
      "Para el que confunde estar ocupado con estar bien. Esto no es sobre productividad.",
    cta: "Escribe 'QUIETUD' y te mando la pregunta que nadie quiere hacerse.",
    keywordManychat: "QUIETUD",
    plataforma: "Instagram",
    estado: "programado",
    fechaPublicacion: "2026-06-17T19:30:00",
    objetivo: "DM",
    formato: "reel",
    anguloPsicologico: "Miedo a la quietud como motor del exceso de trabajo.",
    emocion: "miedo",
    etapaEmbudo: "TOFU",
    assets: ["B-roll oficina vacía", "Plano cerrado a cámara", "Música tensa baja"],
    notasGrabacion: "Grabar en una toma, sin cortes los primeros 5s. Luz lateral dura.",
  },
  {
    id: "p_002",
    tituloInterno: "Carrusel — Éxito vs paz",
    hook: "Tu negocio crece, pero tu paz no.",
    guion:
      "8 slides contrastando métrica externa con estado interno. Último slide: invitación a conversación.",
    descripcion: "Un carrusel para guardar y releer cuando vuelvas a sentirte vacío en la cima.",
    cta: "Guárdalo. Y si te tocó, escríbeme 'PAZ'.",
    keywordManychat: "PAZ",
    plataforma: "Instagram",
    estado: "guion",
    fechaPublicacion: "2026-06-18T13:00:00",
    objetivo: "lead",
    formato: "carrusel",
    anguloPsicologico: "Disociación entre logro y bienestar.",
    emocion: "vacío",
    etapaEmbudo: "MOFU",
    assets: ["Plantilla carrusel oscura", "Tipografía serif para frases clave"],
    notasGrabacion: "Sin foto, solo texto sobre fondo carbón con grano.",
  },
  {
    id: "p_003",
    tituloInterno: "Story — Productividad como anestesia",
    hook: "Dejá de llamar 'productividad' a tu forma de no sentir.",
    guion: "Una frase + sticker de pregunta. Responder en DM con audio.",
    descripcion: "",
    cta: "Responde con una palabra: ¿de qué te distrae tu agenda?",
    keywordManychat: "AGENDA",
    plataforma: "Instagram",
    estado: "programado",
    fechaPublicacion: "2026-06-19T08:30:00",
    objetivo: "interacción",
    formato: "story",
    anguloPsicologico: "Productividad como evitación emocional.",
    emocion: "culpa",
    etapaEmbudo: "TOFU",
    assets: ["Fondo negro", "Sticker pregunta"],
    notasGrabacion: "Publicar 8:30 AM, responder DMs 9-10 AM.",
  },
  {
    id: "p_004",
    tituloInterno: "Reel — Ambición y herida",
    hook: "Eso que llamas ambición también puede ser trauma.",
    guion:
      "Hook → golpe → desarrollo sobre el origen de la ambición → ejemplo → giro de conciencia → cierre → CTA.",
    descripcion: "No para quitarte la ambición. Para que sepas a quién le pertenece.",
    cta: "Escribe 'RAÍZ' y hablamos.",
    keywordManychat: "RAIZ",
    plataforma: "TikTok",
    estado: "idea",
    fechaPublicacion: "2026-06-20T20:00:00",
    objetivo: "alcance",
    formato: "reel",
    anguloPsicologico: "Ambición como respuesta a una herida de no-suficiencia.",
    emocion: "dolor",
    etapaEmbudo: "TOFU",
    assets: ["Plano fijo", "Subtítulos grandes"],
    notasGrabacion: "Versión TikTok más cruda que la de IG.",
  },
  {
    id: "p_005",
    tituloInterno: "Email — La cima vacía",
    hook: "Llegaste arriba y nadie te avisó del silencio.",
    guion:
      "Email corto en segunda persona. Historia breve. Una sola idea. CTA a responder el correo.",
    descripcion: "Newsletter semanal.",
    cta: "Responde este correo con una palabra: ¿qué evitas sentir?",
    keywordManychat: "",
    plataforma: "Email",
    estado: "editado",
    fechaPublicacion: "2026-06-19T07:00:00",
    objetivo: "lead",
    formato: "email",
    anguloPsicologico: "Vacío en la cima del logro.",
    emocion: "vacío",
    etapaEmbudo: "MOFU",
    assets: ["Plantilla email texto plano"],
    notasGrabacion: "Sin imágenes. Texto plano, como una carta.",
  },
  {
    id: "p_006",
    tituloInterno: "Reel — No es disciplina",
    hook: "No es disciplina. Es huida con buena reputación.",
    guion: "Hook → desmontar disciplina → ejemplo → giro → CTA.",
    descripcion: "Para el adicto al trabajo que se cree disciplinado.",
    cta: "Comenta 'HUIDA'.",
    keywordManychat: "HUIDA",
    plataforma: "YouTube Shorts",
    estado: "grabado",
    fechaPublicacion: "2026-06-21T18:00:00",
    objetivo: "alcance",
    formato: "reel",
    anguloPsicologico: "Disciplina como defensa contra el contacto interno.",
    emocion: "verdad",
    etapaEmbudo: "TOFU",
    assets: ["Versión vertical 9:16", "Hook visible primeros 2s"],
    notasGrabacion: "Reusar grabación de IG, recortar para Shorts.",
  },
];

// ============================ 6. TENDENCIAS (ejemplos) ============================

export const tendencias: Tendencia[] = [
  {
    id: "t_001",
    titulo: "Nuevos modelos de Claude para razonamiento largo",
    fuente: "Blog de Anthropic",
    link: "https://www.anthropic.com/news",
    fecha: "2026-06-16",
    resumen:
      "Anthropic publica mejoras en razonamiento extendido. Tema caliente sobre IA y trabajo cognitivo.",
    nivelPotencial: 7,
    porQueSirve:
      "Puente entre IA y psicología: si la máquina piensa por ti, ¿qué haces tú con tu mente?",
    comoAdaptarla:
      "Ángulo: 'delegamos el pensar a la IA, pero seguimos sin poder estar 5 minutos a solas'.",
    posibleHook: "La IA ya piensa por ti. Lo que no resuelve es por qué no te soportas en silencio.",
    posibleReel: "Reel sobre delegar tareas vs delegar tu vida interior.",
    posibleCarrusel: "7 cosas que la IA puede hacer por ti y 1 que jamás hará.",
    posibleStory: "Encuesta: ¿usas IA para no pensar o para pensar mejor?",
    etiqueta: "potencial de gancho",
  },
  {
    id: "t_002",
    titulo: "Sube el formato 'carta de voz' en Instagram",
    fuente: "Tendencias de Instagram",
    link: "https://instagram.com",
    fecha: "2026-06-16",
    resumen:
      "Crece el reel hablado a cámara, sin edición, tipo confesión. Penaliza el over-editing.",
    nivelPotencial: 9,
    porQueSirve: "Tu marca vive de la verdad cruda. Este formato es tu terreno natural.",
    comoAdaptarla: "Serie 'cartas a un fundador que se está rompiendo'. Una toma, sin música.",
    posibleHook: "Si llevas meses sintiéndote vacío con todo funcionando, esto es para ti.",
    posibleReel: "Carta de voz de 60s mirando a cámara, fondo negro.",
    posibleCarrusel: "—",
    posibleStory: "Detrás del primer 'carta de voz'.",
    etiqueta: "emocional",
  },
  {
    id: "t_003",
    titulo: "Debate viral: 'la rutina matutina como nueva religión'",
    fuente: "X / Twitter",
    link: "https://x.com",
    fecha: "2026-06-15",
    resumen: "Hilo polémico sobre el culto a la rutina y la autooptimización.",
    nivelPotencial: 8,
    porQueSirve: "Choca de frente con tu tesis: optimización como huida.",
    comoAdaptarla: "Ángulo polémico: 'tu rutina de 5am no es disciplina, es miedo a la pausa'.",
    posibleHook: "Tu rutina perfecta es el lugar más sofisticado donde escondes tu ansiedad.",
    posibleReel: "Reel contra la cultura de la autooptimización.",
    posibleCarrusel: "La diferencia entre orden y control.",
    posibleStory: "¿Tu rutina te sostiene o te ata?",
    etiqueta: "polémico",
  },
  {
    id: "t_004",
    titulo: "Tema: soledad emocional en fundadores",
    fuente: "Newsletter de marketing/psicología",
    link: "https://example.com/estudio",
    fecha: "2026-06-15",
    resumen: "Tema recurrente: el aislamiento emocional pese al éxito en dueños de negocio.",
    nivelPotencial: 8,
    porQueSirve: "Conecta directo con el dolor central de tu avatar.",
    comoAdaptarla: "Abrir con el tema y aterrizarlo en una historia personal (sin inventar cifras).",
    posibleHook: "Tener todo funcionando y aun así sentirte solo no es desagradecimiento. Es una señal.",
    posibleReel: "Reel reflexivo sobre la soledad del que lidera.",
    posibleCarrusel: "El precio invisible de construir algo grande.",
    posibleStory: "¿Te sientes solo aunque todo va bien?",
    etiqueta: "explicativo",
  },
  {
    id: "t_005",
    titulo: "Sonido en tendencia: piano melancólico lo-fi",
    fuente: "Tendencias de TikTok",
    link: "https://tiktok.com",
    fecha: "2026-06-16",
    resumen: "Audio en alza ideal para contenido reflexivo e introspectivo.",
    nivelPotencial: 7,
    porQueSirve: "Encaja con el tono de tus piezas más reflexivas.",
    comoAdaptarla: "Usar como cama sonora en 'cartas de voz' y reflexiones.",
    posibleHook: "—",
    posibleReel: "Reflexión introspectiva con este audio de fondo bajo.",
    posibleCarrusel: "—",
    posibleStory: "—",
    etiqueta: "potencial de gancho",
  },
  {
    id: "t_006",
    titulo: "Ola de contenido 'anti-mindfulness de plástico'",
    fuente: "Temas virales del nicho",
    link: "https://example.com/anti-mindfulness",
    fecha: "2026-06-14",
    resumen: "Crece la crítica a la espiritualidad comercial y el 'positivismo tóxico'.",
    nivelPotencial: 6,
    porQueSirve: "Coherente con tu 'espiritualidad cruda', pero cuida el tono para no atacar.",
    comoAdaptarla: "Ofrecer espejo, no juicio. Mostrar la alternativa con verdad.",
    posibleHook: "La espiritualidad de moda te vendió calma. Lo que necesitabas era verdad.",
    posibleReel: "Reel sobre buscar paz vs buscar verdad.",
    posibleCarrusel: "5 frases espirituales que en realidad son evitación.",
    posibleStory: "¿Meditas para sentir o para no sentir?",
    etiqueta: "polémico",
  },
];

// ============================ 8. IDEAS (ejemplos) ============================

export const ideas: Idea[] = [
  {
    id: "i_001",
    idea: "La diferencia entre estar solo y estar sin máscara.",
    categoria: "identidad",
    emocion: "verdad",
    nivelPotencia: 8,
    etapaEmbudo: "TOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-15",
    estado: "convertir en hook",
  },
  {
    id: "i_002",
    idea: "Por qué el dinero amplifica quién ya eras, no te arregla.",
    categoria: "dinero",
    emocion: "verdad",
    nivelPotencia: 7,
    etapaEmbudo: "MOFU",
    posibleFormato: "carrusel",
    origen: "Ejemplo",
    fecha: "2026-06-14",
    estado: "buena",
  },
  {
    id: "i_003",
    idea: "El control no es seguridad, es desconfianza con disfraz de orden.",
    categoria: "sombra",
    emocion: "miedo",
    nivelPotencia: 9,
    etapaEmbudo: "TOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-13",
    estado: "convertir en guion",
  },
  {
    id: "i_004",
    idea: "Pedir ayuda y la herida masculina de 'yo puedo solo'.",
    categoria: "ego",
    emocion: "vergüenza",
    nivelPotencia: 8,
    etapaEmbudo: "MOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-12",
    estado: "cruda",
  },
  {
    id: "i_005",
    idea: "El burnout no es por trabajar mucho, es por trabajar desconectado.",
    categoria: "negocio",
    emocion: "vacío",
    nivelPotencia: 7,
    etapaEmbudo: "TOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-11",
    estado: "buena",
  },
  {
    id: "i_006",
    idea: "Cómo el apego se disfraza de 'amor que todo lo aguanta'.",
    categoria: "apego",
    emocion: "dolor",
    nivelPotencia: 8,
    etapaEmbudo: "MOFU",
    posibleFormato: "carrusel",
    origen: "Ejemplo",
    fecha: "2026-06-10",
    estado: "convertir en hook",
  },
  {
    id: "i_007",
    idea: "La ansiedad como mensajera: qué intenta decirte antes de medicarla.",
    categoria: "ansiedad",
    emocion: "miedo",
    nivelPotencia: 6,
    etapaEmbudo: "BOFU",
    posibleFormato: "email",
    origen: "Ejemplo",
    fecha: "2026-06-09",
    estado: "cruda",
  },
  {
    id: "i_008",
    idea: "Disciplina con amor vs disciplina como castigo a quien fuiste.",
    categoria: "disciplina",
    emocion: "culpa",
    nivelPotencia: 7,
    etapaEmbudo: "TOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-08",
    estado: "buena",
  },
  {
    id: "i_009",
    idea: "El propósito que persigues, ¿es tuyo o es la deuda de un niño herido?",
    categoria: "propósito",
    emocion: "verdad",
    nivelPotencia: 9,
    etapaEmbudo: "MOFU",
    posibleFormato: "reel",
    origen: "Ejemplo",
    fecha: "2026-06-07",
    estado: "convertir en guion",
  },
  {
    id: "i_010",
    idea: "Frase suelta: 'la madurez es dejar de cobrarle a otros lo que te debías a ti'.",
    categoria: "trauma",
    emocion: "alivio",
    nivelPotencia: 6,
    etapaEmbudo: "TOFU",
    posibleFormato: "story",
    origen: "Ejemplo",
    fecha: "2026-06-06",
    estado: "cruda",
  },
];

// ============================ 9. DIAGNÓSTICO ============================
// Vacío a propósito: el diagnóstico se construye a partir de TUS métricas
// reales. La página muestra un estado inicial hasta que registres datos.

export const diagnosticoSemanal: DiagnosticoSemanal = {
  id: "",
  semana: "",
  loQueFunciono: [],
  loQueNoFunciono: [],
  patronDetectado: "",
  hipotesis: "",
  proximoExperimento: "",
  ideasNuevas: [],
  hooksRecomendados: [],
  decisionEstrategica: "",
};

// ----- Constantes de UI reutilizables -----

export const PLATAFORMAS = [
  "Instagram",
  "TikTok",
  "YouTube Shorts",
  "Threads",
  "WhatsApp Community",
  "Email",
] as const;

export const EMOCIONES = [
  "dolor",
  "culpa",
  "miedo",
  "vacío",
  "rabia",
  "vergüenza",
  "esperanza",
  "alivio",
  "curiosidad",
  "verdad",
] as const;

export const NICHOS = [
  "ego",
  "trauma",
  "identidad",
  "sombra",
  "relaciones",
  "conciencia",
  "espiritualidad",
  "negocio",
  "ansiedad",
  "dinero",
  "propósito",
  "disciplina",
  "autosabotaje",
] as const;

export const TIPOS_GANCHO = [
  "Dejá de hacer [X]",
  "[X] está matando tu [Y]",
  "[Número] cosas que ojalá hubiera sabido",
  "Nadie te dice esto sobre [X]",
  "El problema no es [X], es [Y]",
  "No estás cansado, estás [X]",
  "Tu negocio crece, pero tu paz no",
  "No es disciplina, es huida",
  "No quieres amor, quieres anestesia",
  "Eso que llamas ambición también puede ser trauma",
] as const;

export const FORMATOS = ["reel", "carrusel", "story", "thread", "email"] as const;

export const ESTADOS_PIEZA = [
  "idea",
  "guion",
  "grabado",
  "editado",
  "programado",
  "publicado",
] as const;

export const OBJETIVOS = ["alcance", "interacción", "DM", "lead", "venta"] as const;

export const ETAPAS_EMBUDO = ["TOFU", "MOFU", "BOFU"] as const;
